### ISSUE TITLE
Problems compiling to CSS

### ISSUE THREAD

**Issue by rawzone** [michowski/flexible-gs#1]
Hi,

Seems like I get an error when trying to compile this to CSS.

Using node-sass@3.7.0 under node v6.2.0

```
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend %flexible-column" on line 147 of resources/assets/sass/partials/_flexible-gs.scss
        on line 101 of resources/assets/sass/partials/_flexible-gs.scss
>>     %flexible-column {
   ----^
```

**Comment by michowski** [comment]
Hello rawzone. I hope you have a good day.

Yes, there was an error for node-sass which I haven't notice, because I've been using Ruby compiler. It is nothing but a lack of support in node-sass/Libsass for SASS placeholders used with `@extend` and `@at-root(without: media)` inside media queries. 

I had to completely rewrite the main part of code and use a boilerplate workaround with a map containing all breakpoints, selectors and their properties. I think it's the only way to achieve this effect in SASS.

Thank you very much for your feedback, I really appreciate that! I hope now it's working for you.

**Comment by rawzone** [comment]
Sorry for the late response! Your fix worked like a charm, now compiles fast an error less to css.

Will be trying it out in a new little project i have started, seems like a decent pick for a drop i grid system that is not filled with useless stuff.

Thanks for the quick update and will keep you informed if i find any other problems!

**Comment by michowski** [comment]
Hello :) . Great to hear that from you! I really appreciate your feedback and I'm glad it's working now.

Good luck and have fun using Flexible!
